const productos = [
    {
        id: 1,
        imagen: "./img/pothos.jpg",
        nombre: 'Potho',
        descripcion: 'Planta de hojas verdes y flores blancas, excelente para ambientes tranquilos.',
        precio: 6,
        stock: 2,
    },
    {
        id: 2,
        imagen: "./img/lirio.jpg",
        nombre: 'Lirio de la Paz',
        descripcion: 'Planta de hojas verdes y flores blancas, excelente para ambientes tranquilos.',
        precio: 15,
        stock: 15,
    },
    {
        id: 3,
        imagen: "./img/sansevieria.jpg",
        nombre: 'Sansevieria',
        descripcion: 'Cuidado muy fácil, familia de las suculentas. Purifica el aire, requiere poco riego y semisombra.',
        precio: 12,
        stock: 12,
    },
    {
        id: 4,
        imagen: "./img/Anturio rojo.jpeg",
        nombre: 'Anturio rojo',
        descripcion: 'Planta exótica con flores rojas vibrantes, excelente para decoración interior.',
        precio: 20,
        stock: 10,
    },
    {
        id: 5,
        imagen: "./img/ficus.jpg",
        nombre: 'Ficus',
        descripcion: 'Planta resistente con hojas brillantes, ideal para purificar el aire en espacios interiores.',
        precio: 12,
        stock: 7,
    },
    {
        id: 6,
        imagen: "./img/monstera.jpg",
        nombre: 'Costilla de Adán',
        descripcion: 'Planta tropical de hojas grandes y divididas, perfecta para interiores luminosos.',
        precio: 25,
        stock: 8,
    },
    {
        id: 7,
        imagen: "./img/Boston.jpg",
        nombre: 'Helecho Boston',
        descripcion: 'Planta colgante con hojas suaves, ideal para ambientes húmedos y semisombra.',
        precio: 18,
        stock: 12,
    },
    {
        id: 8,
        imagen: "./img/palma.jpg",
        nombre: 'Palma Areca',
        descripcion: 'Planta ornamental de crecimiento lento, perfecta para interiores amplios y luminosos',
        precio: 35,
        stock: 8,
    },
    {
        id: 9,
        imagen: "./img/calathea.jpg",
        nombre: 'Calathea Orbifolia',
        descripcion: 'Planta tropical con hojas grandes y rayadas, requiere alta humedad.',
        precio: 28,
        stock: 5,
    },
    {
        id: 10,
        imagen: "./img/geranio.jpeg",
        nombre: 'Geranio',
        descripcion: 'Planta de flores coloridas, ideal para exteriores luminosos y climas cálidos. ',
        precio: 16,
        stock: 6,
    },
    {
        id: 11,
        imagen: "./img/hoya.jpg",
        nombre: 'Hoya Kerrii',
        descripcion: 'Suculenta en forma de corazón, crece lentamente y es perfecta para interiores. ',
        precio: 16,
        stock: 7,
    },

    {
        id: 12,
        imagen: "./img/peperomia.jpg",
        nombre: 'Peperomia',
        descripcion: 'Suculenta de hojas gruesas y cerosas, resistente y de bajo mantenimiento.',
        precio: 16,
        stock: 5,
    },
];

